version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: mariadb
    container_name: db
    restart: always
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_HOST=root
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    command: --bind-address=0.0.0.0