spring:
  datasource:
    url: jdbc:mariadb://host.docker.internal:3306/mydb?useUnicode=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: password
  sql:
    init:
      mode: always
      encoding: UTF-8
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
        dialect: org.hibernate.dialect.MariaDBDialect
        format-sql: true
        show-sql: true
    defer-datasource-initialization: true